version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "helloWorldLambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15nlpkuwgyngi"
s3_prefix = "helloWorldLambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=045643545213.dkr.ecr.us-east-1.amazonaws.com/helloworldlambda2e6fefd6/helloworldfunction19d43fc4repo"]
